#!/usr/bin/env python3
import os
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import Empty
import ros_numpy # pip3 install git+https://github.com/eric-wieser/ros_numpy
from cv_bridge import CvBridge
from threading import Lock
import cv2


bridge = CvBridge()

image_lock = Lock()

image = None

rospy.init_node('visualization_node')
pub = rospy.Publisher('image', Image, queue_size=0)

def rcv_image(msg):
    global image
    rospy.loginfo('image here')
    image_lock.acquire()
    image = ros_numpy.numpify(msg)
    image_lock.release()
    #cv2.imshow('Image', image)
    #cv2.waitKey(100)
    image_message = bridge.cv2_to_imgmsg(image, encoding="passthrough")
    pub.publish(image_message)

si = rospy.Subscriber('/pepper_robot/camera/front/camera/image_raw', Image, rcv_image) # Stream incoming from pepper front camera
# si = rospy.Subscriber('/test/image_raw', Image, rcv_image)


rospy.spin()
